import { constants } from '../constants';

describe('Register tests', function() {
    it('Empty data test', function(){
        cy.visit(constants.URL)
        cy.get('[href="/register"]').click()
        cy.url().should('include', '/register')
        cy.get('.makeStyles-register-6').click()
        cy.url().should('include', '/register')
        cy.contains('Imię jest wymaganym polem')
        cy.contains('Nazwisko jest wymaganym polem')
        cy.contains('Nick jest wymaganym polem')
        cy.contains('Email jest wymaganym polem')
        cy.contains('Hasło jest wymaganym polem')
        cy.contains('Potwierdzenie hasła jest wymaganym polem')
    })
    
    it('Invalid email test', function(){
        cy.visit(constants.URL)
        cy.get('[href="/register"]').click()
        cy.url().should('include', '/register')
        cy.get(':nth-child(11) > .MuiFilledInput-root > #filled-multiline-flexible').type('test')
        cy.get('.makeStyles-register-6').click()
        // TODO: Find way to read popup
    })
    
    it('Login link test', function(){
        cy.visit(constants.URL)
        cy.get('[href="/register"]').click()
        cy.url().should('include', '/register')
        cy.get('.makeStyles-box-2 > .MuiTypography-root')
        .contains("Masz już konto?").click()
        cy.url().should('include', '/login')
    })

    it('Valid data test', function(){
        cy.visit(constants.URL)
        cy.get('[href="/register"]').click()
        cy.url().should('include', '/register')
        cy.get(':nth-child(2) > .MuiFilledInput-root > #filled-multiline-flexible')
        .type('Adam')
        cy.get(':nth-child(5) > .MuiFilledInput-root > #filled-multiline-flexible')
        .type('Nowak')
        cy.get(':nth-child(8) > .MuiFilledInput-root > #filled-multiline-flexible')
        .type('adno')
        cy.get(':nth-child(11) > .MuiFilledInput-root > #filled-multiline-flexible')
        .type('anowak@wp.pl')
        cy.get(':nth-child(14) > .MuiFilledInput-root > #filled-multiline-flexible')
        .type('haslomaslo')
        cy.get(':nth-child(17) > .MuiFilledInput-root > #filled-multiline-flexible')
        .type('haslomaslo')
        cy.get('.makeStyles-register-6').click()
    })

    it('Test cant register second time', function(){
        cy.visit(constants.URL)
        cy.get('[href="/register"]').click()
        cy.url().should('include', '/register')
        cy.get(':nth-child(2) > .MuiFilledInput-root > #filled-multiline-flexible')
        .type('Adam')
        cy.get(':nth-child(5) > .MuiFilledInput-root > #filled-multiline-flexible')
        .type('Nowak')
        cy.get(':nth-child(8) > .MuiFilledInput-root > #filled-multiline-flexible')
        .type('adno')
        cy.get(':nth-child(11) > .MuiFilledInput-root > #filled-multiline-flexible')
        .type('anowak@wp.pl')
        cy.get(':nth-child(14) > .MuiFilledInput-root > #filled-multiline-flexible')
        .type('haslomaslo')
        cy.get(':nth-child(17) > .MuiFilledInput-root > #filled-multiline-flexible')
        .type('haslomaslo')
        cy.get('.makeStyles-register-6').click()
        cy.get('.MuiAlert-message').
        contains('Użytkownik o tym nicku już istnieje w bazie danych. Spróbuj innej nazwy')
        .should('exist')
    })

    it('Test new user login', function(){
        cy.visit(constants.URL)
        cy.contains("Zaloguj").should('exist')
        cy.contains("Zaloguj").click()
        cy.url().should('include', '/login')
        cy.get('input[name=username]').type('adno')
        cy.get('input[name=password]').type('haslomaslo')
        cy.contains("Login").should('exist')
        cy.contains("Login").click()
        cy.contains("Wyloguj")
        cy.contains("Home Screen")
    })
})